version: '2'
services:

  jupyter:
    build: ./jupyterhub
    ports:
      - "8000:8000"
    links:
      - postgis:postgishost
    volumes:
      - "./data/jupyterhome:/home/jupyter"

  postgis:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=urbis
      - POSTGRES_DB=urbis
      - POSTGRES_USER=urbis
      - PGDATA=/var/local/pgdata
    ports:
      - "25432:5432"
    volumes:
      - "./data/pgdata:/var/local/pgdata"

  urbisnode:
    build: ./urbisnode
    volumes:
      - "./urbisnode/urbisnode/:/var/local/urbisnode/"
    ports:
      - "3003:3003"
    working_dir: /var/local/urbisnode
    command: npm start

